// Writer-portal copy, English and Spanish.
//
// Most of this publisher's roster is Spanish-speaking, so Spanish is a first
// class version of the portal rather than a machine-translated afterthought.
// A few notes on the choices below, because royalty vocabulary is where
// literal translations go wrong:
//
//   "Royalties earned"       -> "Regalías generadas"  (not "ganadas": the money
//                               was generated by usage, not won)
//   "Brought forward"        -> "Saldo anterior"      (standard accounting term
//                               on Spanish-language statements)
//   "Carried to next period" -> "Traspaso al siguiente período"
//   "Recouped"               -> "Recuperado"          (advance recoupment)
//   "Commission"             -> "Comisión"
//   "Net payable to you"     -> "Neto a pagarte"
//
// Keys are dotted and grouped by area. A missing key falls back to English,
// then to the key itself — a half-translated screen is better than a blank one.

const translations = {
  en: {
    'nav.royalties': 'Royalties',
    'nav.statements': 'Statements',
    'nav.settings': 'Settings',
    'nav.signOut': 'Sign Out',
    'nav.lightMode': 'Light Mode',
    'nav.darkMode': 'Dark Mode',

    'earnings.title': 'Earnings',
    'earnings.netPayable': 'Net payable to you',
    'earnings.totalRevenue': 'Total Revenue',
    'earnings.viewStatements': 'View Statements',
    'earnings.export': 'Export',

    'waterfall.grossEarned': 'Royalties earned',
    'waterfall.broughtForward': 'Brought forward',
    'waterfall.recouped': 'Recouped',
    'waterfall.carriedForward': 'Carried to next period',
    'waterfall.commission': 'Commission',
    'waterfall.netPayable': 'Net payable',

    'payout.belowMinimumTitle': 'Balance below the {min} minimum.',
    'payout.belowMinimumBody':
      'Your payable balance of {balance} is under {min}, so it is carried forward to the next period — no payment is made until your balance reaches {min}.',
    'common.dismiss': 'Dismiss',

    'statements.title': 'Statements',
    'statements.emptyTitle': 'No statements available yet',
    'statements.emptyBody': 'Statements appear here once distributed to a writer.',
    'statements.colStatement': 'Statement',
    'statements.colPeriod': 'Period',
    'statements.colDate': 'Statement date',
    'statements.colAmount': 'Amount',
    'statements.subtitle': 'Download the royalty statements your publisher has distributed to you.',
    'statements.pendingBody':
      'Your {period} statement is being finalised by your publisher. Once it is distributed it will appear here, ready to download.',

    'statements.subtitleNamed': 'Royalty statements distributed to {name} by your publisher.',
    'statements.totalDistributed': 'Total distributed',
    'statements.loading': 'Loading your statements…',
    'statements.emptyBodyLive':
      'Your statements are being finalised by your publisher. Once they are distributed they will appear here, ready to download.',
    'statements.colDistributed': 'Distributed',
    'statements.download': 'Download PDF',
    'statements.downloading': 'Downloading…',
    'statements.downloadCsv': 'Download CSV',
    'statements.loadError': 'Could not load your statements.',
    'statements.downloadError': 'That statement could not be downloaded.',

    'access.title': 'Who has access',
    'access.subtitle': 'Invite your manager or attorney to view these statements.',
    'access.guestNote': 'Only the primary contact for this client can change who has access.',
    'access.emailPlaceholder': 'name@example.com',
    'access.role': 'Role',
    'access.role.primary': 'Primary',
    'access.role.manager': 'Manager',
    'access.role.legal': 'Legal',
    'access.role.other': 'Other',
    'access.send': 'Send invite',
    'access.sending': 'Sending…',
    'access.statusActive': 'Active',
    'access.statusInvited': 'Invited',
    'access.revoke': 'Revoke',
    'access.empty': 'Nobody else has access yet.',
    'access.inviteFailed': 'Could not send that invite.',
    'access.revokeFailed': 'Could not revoke that invite.',
    'access.linkNote': 'Emailed to {email} — or send them this link yourself',
    'access.copy': 'Copy',
    'access.copied': 'Copied',
    'access.you': 'you',

    'earnings.subtitle': 'Your royalties, by period, song and territory.',
    'earnings.period': 'Period',
    'earnings.all': 'All',
    'earnings.works': 'Works',
    'earnings.topPlatforms': 'Top 3 Platforms',
    'earnings.topTerritories': 'Top 3 Territories',
    'earnings.revenueOverTime': 'Revenue Over Time',
    'earnings.revenueBySource': 'Revenue by Source',
    'earnings.incomeType': 'Income Type',
    'earnings.organization': 'Organization',
    'earnings.noData': 'No data to display',
    'earnings.revenueByTerritory': 'Revenue by Territory',
    'earnings.globeAlt': 'Interactive globe showing revenue distribution',
    'earnings.topCountries': 'Top 10 Countries by Revenue',
    'earnings.revenueByPlatform': 'Revenue by Platform',
    'earnings.platformSubtitle': 'Revenue breakdown by DSP',
    'earnings.filters': 'Filters',
    'earnings.allIncomeTypes': 'All Income Types',
    'earnings.allTerritories': 'All Territories',
    'earnings.selectAll': 'Select All',
    'earnings.deselectAll': 'Deselect All',
    'earnings.searchSong': 'Search song name…',
    'earnings.searchSongs': 'Search songs, artists, sources...',
    'earnings.sortByAmount': 'Click to sort by amount',
    'earnings.noSongs': 'No songs found with the current filters.',
    'earnings.perPage': 'Per page:',
    'earnings.first': 'First',
    'earnings.previous': 'Previous',
    'earnings.next': 'Next',
    'earnings.last': 'Last',
    'earnings.prevYears': 'Previous years',
    'earnings.nextYears': 'Next years',

    'table.date': 'Date',
    'table.source': 'Source',
    'table.paymentSources': 'Payment Sources',
    'table.territory': 'Territory',
    'table.status': 'Status',

    'income.streaming': 'Streaming',
    'income.download': 'Download',
    'income.physical': 'Physical',
    'income.performance': 'Performance',
    'income.mechanical': 'Mechanical',
    'income.sync': 'Sync',
    'income.merchandise': 'Merchandise',
    'income.live': 'Live',
    'income.other': 'Other',

    'earnings.subtitleLive':
      'Where your royalties came from. Charts below show gross earnings by source — your net payable is above.',
    'earnings.showingRange': 'Showing {from}-{to} of {total} transactions ({pages} pages total)',
    'earnings.pageOf': 'Page {page} of {pages}',
    'table.amount': 'Amount',

    'lang.label': 'Language',
    'lang.en': 'EN',
    'lang.es': 'ES',
    'lang.switchToSpanish': 'Cambiar a español',
    'lang.switchToEnglish': 'Switch to English',
  },

  es: {
    'nav.royalties': 'Regalías',
    'nav.statements': 'Estados de cuenta',
    'nav.settings': 'Configuración',
    'nav.signOut': 'Cerrar sesión',
    'nav.lightMode': 'Modo claro',
    'nav.darkMode': 'Modo oscuro',

    'earnings.title': 'Ingresos',
    'earnings.netPayable': 'Neto a pagarte',
    'earnings.totalRevenue': 'Ingresos totales',
    'earnings.viewStatements': 'Ver estados de cuenta',
    'earnings.export': 'Exportar',

    'waterfall.grossEarned': 'Regalías generadas',
    'waterfall.broughtForward': 'Saldo anterior',
    'waterfall.recouped': 'Recuperado',
    'waterfall.carriedForward': 'Traspaso al siguiente período',
    'waterfall.commission': 'Comisión',
    'waterfall.netPayable': 'Neto a pagar',

    'payout.belowMinimumTitle': 'Saldo por debajo del mínimo de {min}.',
    'payout.belowMinimumBody':
      'Tu saldo a pagar de {balance} es inferior a {min}, por lo que se traspasa al siguiente período — no se realiza ningún pago hasta que tu saldo alcance {min}.',
    'common.dismiss': 'Descartar',

    'statements.title': 'Estados de cuenta',
    'statements.emptyTitle': 'Aún no hay estados de cuenta',
    'statements.emptyBody': 'Los estados de cuenta aparecen aquí una vez distribuidos al escritor.',
    'statements.colStatement': 'Estado de cuenta',
    'statements.colPeriod': 'Período',
    'statements.colDate': 'Fecha del estado',
    'statements.colAmount': 'Importe',
    'statements.subtitle': 'Descarga los estados de regalías que tu editorial te ha distribuido.',
    'statements.pendingBody':
      'Tu estado de cuenta de {period} está siendo finalizado por tu editorial. Una vez distribuido aparecerá aquí, listo para descargar.',

    'statements.subtitleNamed': 'Estados de regalías distribuidos a {name} por tu editorial.',
    'statements.totalDistributed': 'Total distribuido',
    'statements.loading': 'Cargando tus estados de cuenta…',
    'statements.emptyBodyLive':
      'Tu editorial está finalizando tus estados de cuenta. Una vez distribuidos aparecerán aquí, listos para descargar.',
    'statements.colDistributed': 'Distribuido',
    'statements.download': 'Descargar PDF',
    'statements.downloading': 'Descargando…',
    'statements.downloadCsv': 'Descargar CSV',
    'statements.loadError': 'No se pudieron cargar tus estados de cuenta.',
    'statements.downloadError': 'No se pudo descargar ese estado de cuenta.',

    'access.title': 'Quién tiene acceso',
    'access.subtitle': 'Invita a tu representante o abogado a ver estos estados de cuenta.',
    'access.guestNote': 'Solo el contacto principal de este cliente puede cambiar quién tiene acceso.',
    'access.emailPlaceholder': 'nombre@ejemplo.com',
    'access.role': 'Rol',
    'access.role.primary': 'Principal',
    'access.role.manager': 'Representante',
    'access.role.legal': 'Legal',
    'access.role.other': 'Otro',
    'access.send': 'Enviar invitación',
    'access.sending': 'Enviando…',
    'access.statusActive': 'Activo',
    'access.statusInvited': 'Invitado',
    'access.revoke': 'Revocar',
    'access.empty': 'Nadie más tiene acceso todavía.',
    'access.inviteFailed': 'No se pudo enviar esa invitación.',
    'access.revokeFailed': 'No se pudo revocar esa invitación.',
    'access.linkNote': 'Enviado por correo a {email} — o envíale tú este enlace',
    'access.copy': 'Copiar',
    'access.copied': 'Copiado',
    'access.you': 'tú',

    'earnings.subtitle': 'Tus regalías, por período, canción y territorio.',
    'earnings.period': 'Período',
    'earnings.all': 'Todos',
    'earnings.works': 'Obras',
    'earnings.topPlatforms': 'Top 3 plataformas',
    'earnings.topTerritories': 'Top 3 territorios',
    'earnings.revenueOverTime': 'Ingresos a lo largo del tiempo',
    'earnings.revenueBySource': 'Ingresos por fuente',
    'earnings.incomeType': 'Tipo de ingreso',
    'earnings.organization': 'Organización',
    'earnings.noData': 'No hay datos para mostrar',
    'earnings.revenueByTerritory': 'Ingresos por territorio',
    'earnings.globeAlt': 'Globo interactivo con la distribución de ingresos',
    'earnings.topCountries': 'Top 10 países por ingresos',
    'earnings.revenueByPlatform': 'Ingresos por plataforma',
    'earnings.platformSubtitle': 'Desglose de ingresos por plataforma digital',
    'earnings.filters': 'Filtros',
    'earnings.allIncomeTypes': 'Todos los tipos de ingreso',
    'earnings.allTerritories': 'Todos los territorios',
    'earnings.selectAll': 'Seleccionar todo',
    'earnings.deselectAll': 'Deseleccionar todo',
    'earnings.searchSong': 'Buscar por título…',
    'earnings.searchSongs': 'Buscar canciones, artistas, fuentes...',
    'earnings.sortByAmount': 'Haz clic para ordenar por importe',
    'earnings.noSongs': 'No se encontraron canciones con los filtros actuales.',
    'earnings.perPage': 'Por página:',
    'earnings.first': 'Primera',
    'earnings.previous': 'Anterior',
    'earnings.next': 'Siguiente',
    'earnings.last': 'Última',
    'earnings.prevYears': 'Años anteriores',
    'earnings.nextYears': 'Años siguientes',

    'table.date': 'Fecha',
    'table.source': 'Fuente',
    'table.paymentSources': 'Fuentes de pago',
    'table.territory': 'Territorio',
    'table.status': 'Estado',

    'income.streaming': 'Streaming',
    'income.download': 'Descarga',
    'income.physical': 'Físico',
    'income.performance': 'Ejecución pública',
    'income.mechanical': 'Mecánicas',
    'income.sync': 'Sincronización',
    'income.merchandise': 'Merchandising',
    'income.live': 'En vivo',
    'income.other': 'Otros',

    'earnings.subtitleLive':
      'De dónde provienen tus regalías. Los gráficos muestran los ingresos brutos por fuente — tu neto a pagar está arriba.',
    'earnings.showingRange': 'Mostrando {from}-{to} de {total} transacciones ({pages} páginas en total)',
    'earnings.pageOf': 'Página {page} de {pages}',
    'table.amount': 'Importe',

    'lang.label': 'Idioma',
    'lang.en': 'EN',
    'lang.es': 'ES',
    'lang.switchToSpanish': 'Cambiar a español',
    'lang.switchToEnglish': 'Switch to English',
  },
};

export const SUPPORTED_LANGUAGES = ['en', 'es'];
export const DEFAULT_LANGUAGE = 'en';

export default translations;
