// Writer-portal copy, English and Spanish.
//
// Most of this publisher's roster is Spanish-speaking, so Spanish is a first
// class version of the portal rather than a machine-translated afterthought.
// A few notes on the choices below, because royalty vocabulary is where
// literal translations go wrong:
//
//   "Royalties earned"       -> "Regalías generadas"  (not "ganadas": the money
//                               was generated by usage, not won)
//   "Brought forward"        -> "Saldo anterior"      (standard accounting term
//                               on Spanish-language statements)
//   "Carried to next period" -> "Traspaso al siguiente período"
//   "Recouped"               -> "Recuperado"          (advance recoupment)
//   "Commission"             -> "Comisión"
//   "Net payable to you"     -> "Neto a pagarte"
//
// Keys are dotted and grouped by area. A missing key falls back to English,
// then to the key itself — a half-translated screen is better than a blank one.

const translations = {
  en: {
    'nav.royalties': 'Royalties',
    'nav.statements': 'Statements',
    'nav.settings': 'Settings',
    'nav.signOut': 'Sign Out',
    'nav.lightMode': 'Light Mode',
    'nav.darkMode': 'Dark Mode',

    'earnings.title': 'Earnings',
    'earnings.netPayable': 'Net payable to you',
    'earnings.totalRevenue': 'Total Revenue',
    'earnings.viewStatements': 'View Statements',
    'earnings.export': 'Export',

    'waterfall.grossEarned': 'Royalties earned',
    'waterfall.broughtForward': 'Brought forward',
    'waterfall.recouped': 'Recouped',
    'waterfall.carriedForward': 'Carried to next period',
    'waterfall.commission': 'Commission',
    'waterfall.netPayable': 'Net payable',

    'payout.belowMinimumTitle': 'Balance below the {min} minimum.',
    'payout.belowMinimumBody':
      'Your payable balance of {balance} is under {min}, so it is carried forward to the next period — no payment is made until your balance reaches {min}.',
    'common.dismiss': 'Dismiss',

    'statements.title': 'Statements',
    'statements.emptyTitle': 'No statements available yet',
    'statements.emptyBody': 'Statements appear here once distributed to a writer.',
    'statements.colStatement': 'Statement',
    'statements.colPeriod': 'Period',
    'statements.colDate': 'Statement date',
    'statements.colAmount': 'Amount',
    'statements.subtitle': 'Download the royalty statements your publisher has distributed to you.',
    'statements.pendingBody':
      'Your {period} statement is being finalised by your publisher. Once it is distributed it will appear here, ready to download.',

    'lang.label': 'Language',
    'lang.en': 'EN',
    'lang.es': 'ES',
    'lang.switchToSpanish': 'Cambiar a español',
    'lang.switchToEnglish': 'Switch to English',
  },

  es: {
    'nav.royalties': 'Regalías',
    'nav.statements': 'Estados de cuenta',
    'nav.settings': 'Configuración',
    'nav.signOut': 'Cerrar sesión',
    'nav.lightMode': 'Modo claro',
    'nav.darkMode': 'Modo oscuro',

    'earnings.title': 'Ingresos',
    'earnings.netPayable': 'Neto a pagarte',
    'earnings.totalRevenue': 'Ingresos totales',
    'earnings.viewStatements': 'Ver estados de cuenta',
    'earnings.export': 'Exportar',

    'waterfall.grossEarned': 'Regalías generadas',
    'waterfall.broughtForward': 'Saldo anterior',
    'waterfall.recouped': 'Recuperado',
    'waterfall.carriedForward': 'Traspaso al siguiente período',
    'waterfall.commission': 'Comisión',
    'waterfall.netPayable': 'Neto a pagar',

    'payout.belowMinimumTitle': 'Saldo por debajo del mínimo de {min}.',
    'payout.belowMinimumBody':
      'Tu saldo a pagar de {balance} es inferior a {min}, por lo que se traspasa al siguiente período — no se realiza ningún pago hasta que tu saldo alcance {min}.',
    'common.dismiss': 'Descartar',

    'statements.title': 'Estados de cuenta',
    'statements.emptyTitle': 'Aún no hay estados de cuenta',
    'statements.emptyBody': 'Los estados de cuenta aparecen aquí una vez distribuidos al escritor.',
    'statements.colStatement': 'Estado de cuenta',
    'statements.colPeriod': 'Período',
    'statements.colDate': 'Fecha del estado',
    'statements.colAmount': 'Importe',
    'statements.subtitle': 'Descarga los estados de regalías que tu editorial te ha distribuido.',
    'statements.pendingBody':
      'Tu estado de cuenta de {period} está siendo finalizado por tu editorial. Una vez distribuido aparecerá aquí, listo para descargar.',

    'lang.label': 'Idioma',
    'lang.en': 'EN',
    'lang.es': 'ES',
    'lang.switchToSpanish': 'Cambiar a español',
    'lang.switchToEnglish': 'Switch to English',
  },
};

export const SUPPORTED_LANGUAGES = ['en', 'es'];
export const DEFAULT_LANGUAGE = 'en';

export default translations;
